/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-rest:7.16.0")
    implementation("org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-webapp:7.16.0")
    implementation("org.camunda.bpm:camunda-engine-plugin-spin:7.16.0")
    implementation("org.camunda.spin:camunda-spin-dataformat-all:1.11.0")
    implementation("org.springframework.boot:spring-boot-starter-web:2.5.4")
    implementation("com.h2database:h2:1.4.200")
    implementation("org.springframework.boot:spring-boot-starter-jdbc:2.5.4")
    implementation("javax.xml.bind:jaxb-api:2.3.0")
    implementation ("org.apache.commons:commons-lang3:3.12.0")
    implementation ("org.apache.commons:commons-lang3:3.12.0")

    implementation ("javax.activation:activation:1.1.1")


}

group = "br.com.daione.avaliacao"
version = "1.0.0-SNAPSHOT"
description = "registro"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
